name: Lint

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

defaults:
  run:
    working-directory: randyhub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.3
        
      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
